#! /usr/bin/env perl
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

use strict;
use warnings;

my ($module, $k) = @ARGV;
my %c_modules = map { $_ => 1 } qw(kem indcpa polyvec poly consts rejsample cbd verify symmetric-shake);
my %asm_modules = map { $_ => 1 } qw(basemul fq ntt invntt shuffle);

die "usage: $0 module kyber-k\n"
    unless defined $module && defined $k;
die "invalid ML-KEM AVX2 wrapper module: $module\n"
    unless $c_modules{$module} || $asm_modules{$module};
die "invalid ML-KEM AVX2 KYBER_K: $k\n"
    unless $k =~ /^(?:2|3|4)$/;

my $extension = $asm_modules{$module} ? "S" : "c";
my %level = (2 => 512, 3 => 768, 4 => 1024);
my $out = $asm_modules{$module} && @ARGV > 2 ? $ARGV[-1] : undef;
my $fh;

if (defined $out) {
    open $fh, ">", $out or die "cannot open $out for writing: $!\n";
} else {
    open $fh, ">&", \*STDOUT or die "cannot duplicate stdout: $!\n";
}

print $fh <<"EOF";
/*
 * WARNING: do not edit.
 * Generated by crypto/ml_kem/asm/mlkem_avx2/mkwrapper.pl.
 */
#define KYBER_K $k
EOF

if ($c_modules{$module}) {
    print $fh <<'EOF';
#include "ml_kem_avx2_target.h"
EOF
}

if ($module eq "kem") {
    print $fh <<"EOF";
#define randombytes ossl_ml_kem_$level{$k}_avx2_rand_unsupported
#include "randombytes.h"
void randombytes(uint8_t *out, size_t outlen)
{
    (void)out;
    (void)outlen;
}
EOF
}

print $fh <<"EOF";
#include "$module.$extension"
EOF

close $fh or die "cannot close output: $!\n";
