/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 2020-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_SM2DH_MLKEM768_HYBRIDERR_H
# define OPENSSL_SM2DH_MLKEM768_HYBRIDERR_H
# pragma once

# include <openssl/opensslconf.h>
# include <openssl/symhacks.h>
# include <openssl/cryptoerr_legacy.h>

/*
 * SM2DH_MLKEM768_HYBRID reason codes.
 */
#  define SM2DH_MLKEM768_HYBRID_R_EC_ERROR                        100
#  define SM2DH_MLKEM768_HYBRID_R_MLKEM_ERROR                     101 


#endif
