/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_ZKPBPERR_H
# define OPENSSL_ZKPBPERR_H
# pragma once

# include <openssl/opensslconf.h>
# include <openssl/symhacks.h>
# include <openssl/cryptoerr_legacy.h>



/*
 * ZKP_BP reason codes.
 */
# define ZKP_BP_R_EXCEEDS_GENS_CAPACITY                   106
# define ZKP_BP_R_EXCEEDS_MAX_AGG_NUM                     100
# define ZKP_BP_R_EXCEEDS_MAX_BITS                        101
# define ZKP_BP_R_EXCEEDS_PARTY_CAPACITY                  104
# define ZKP_BP_R_EXCEEDS_PP_CAPACITY                     102
# define ZKP_BP_R_TRANSCRIPT_INIT_FAILED                  103
# define ZKP_BP_R_VARIABLE_DUPLICATED                     107
# define ZKP_BP_R_WITNESS_INVALID                         105

#endif
