/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */


#include <openssl/err.h>
#include <openssl/sm2dh_mlkem768_hybriderr.h>
#include "crypto/sm2dh_mlkem768_hybriderr.h"

#ifndef OPENSSL_NO_SM2DH_MLKEM768_HYBRID

# ifndef OPENSSL_NO_ERR

static const ERR_STRING_DATA SM2DH_MLKEM768_HYBRID_str_reasons[] = {
    {ERR_PACK(ERR_LIB_SM2DH_MLKEM768_HYBRID, 0, SM2DH_MLKEM768_HYBRID_R_EC_ERROR), "ec error"},
    {ERR_PACK(ERR_LIB_SM2DH_MLKEM768_HYBRID, 0, SM2DH_MLKEM768_HYBRID_R_MLKEM_ERROR), "mlkem error"},
    {0, NULL}
};

# endif

int ossl_err_load_SM2DH_MLKEM768_HYBRID_strings(void)
{
# ifndef OPENSSL_NO_ERR
    if (ERR_reason_error_string(SM2DH_MLKEM768_HYBRID_str_reasons[0].error) == NULL)
        ERR_load_strings_const(SM2DH_MLKEM768_HYBRID_str_reasons);
# endif
    return 1;
}
#else
NON_EMPTY_TRANSLATION_UNIT
#endif
