#! /usr/bin/env perl
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

use strict;
use warnings;

my ($module, $mode, $namespace) = @ARGV;
my %modules = map { $_ => 1 } qw(sign poly polyvec packing rejsample rounding hybrid pspm);

die "usage: $0 module dilithium-mode namespace-prefix\n"
    unless defined $module && defined $mode && defined $namespace && @ARGV == 3;
die "invalid ML-DSA AVX2 wrapper module: $module\n"
    unless $modules{$module};
die "invalid ML-DSA AVX2 DILITHIUM_MODE: $mode\n"
    unless $mode =~ /^(?:2|3|5)$/;
die "invalid ML-DSA AVX2 namespace prefix: $namespace\n"
    unless $namespace =~ /^ossl_ml_dsa_(?:44|65|87)_avx2_$/;

print <<"EOF";
/*
 * WARNING: do not edit.
 * Generated by crypto/ml_dsa/asm/ml_dsa_avx2/mkwrapper.pl.
 */
#define DILITHIUM_MODE $mode
#define ML_DSA_AVX2_NAMESPACE $namespace
#include "ml_dsa_avx2_namespace.h"
#include "$module.c"
EOF
